# Base on offical Node.js Alpine image
FROM node:alpine

# Set working directory
WORKDIR /frontend

#Install PM2 globally
RUN npm install --global pm2

#Copy package.json before other files
COPY ./package*.json ./

#Install dependencies
RUN npm install

# Copy all files
COPY ./ ./

# Build app
RUN npm run build

# Expose the listening port
EXPOSE 3000

# Run npm start script with PM2 when container starts
CMD ["npm", "start"]